# Generated by Django 3.1.6 on 2021-05-09 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500, verbose_name='Choice Text')),
                ('vote', models.IntegerField(default=0, verbose_name='Votes')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_choice', to='poll.question')),
            ],
        ),
    ]
